exchange: 'kraken'

trading_pairs:
  - "BTC/USDT"
  - "ETH/USDT"
  - "SOL/USDT"
  - "ADA/USDT"

risk_per_trade: 0.01
stop_loss_atr_multiplier: 2.0
take_profit_atr_multiplier: 4.0

model_type: 'ensemble'